#!/bin/sh
set -e

case "$1" in
    install|configure)
        echo "Adding user nagios to docker group..."
        /usr/sbin/usermod -aG docker nagios > /dev/null 2>&1
        echo "Set ACL permission for user nagios on docker socket..."
        /usr/bin/setfacl -m user:nagios:rw /var/run/docker.sock > /dev/null 2>&1
        ;;
    upgrade|abort-upgrade)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

exit 0
