#!/bin/sh
set -e

case "$1" in
    install|configure)
        ;;
    upgrade|abort-upgrade)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

exit 0
