#!/bin/sh
set -e

case "$1" in
    install|configure)
        wget -O - https://packages.icinga.com/icinga.key | gpg --dearmor -o /usr/share/keyrings/icinga-archive-keyring.gpg --batch --yes

        . /etc/os-release; if [ ! -z ${UBUNTU_CODENAME+x} ]; then DIST="${UBUNTU_CODENAME}"; else DIST="$(lsb_release -c| awk '{print $2}')"; fi; \
        echo "deb [signed-by=/usr/share/keyrings/icinga-archive-keyring.gpg] http://packages.icinga.com/ubuntu icinga-${DIST} main" > \
        /etc/apt/sources.list.d/${DIST}-icinga.list

        echo "deb-src [signed-by=/usr/share/keyrings/icinga-archive-keyring.gpg] http://packages.icinga.com/ubuntu icinga-${DIST} main" >> \
        /etc/apt/sources.list.d/${DIST}-icinga.list

        sleep 5

        apt-get update

        exit 0
        ;;
    upgrade|abort-upgrade)
        ;;
    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

exit 0
