#!/bin/sh
set -e

case "$1" in
    install|configure)
        . /etc/os-release
	if [[ ${ID} == "ubuntu" ]]; then
            if [ ! -z ${UBUNTU_CODENAME+x} ]; then
                DIST="${UBUNTU_CODENAME}"
            else
                DIST="$(lsb_release -c| awk '{print $2}')"
            fi

            if [ ! -f "/etc/apt/sources.list.d/${DIST}-icinga.list" ]; then
                wget -O - https://packages.icinga.com/icinga.key | apt-key add -
                echo "deb http://packages.icinga.com/ubuntu icinga-${DIST} main" > /etc/apt/sources.list.d/${DIST}-icinga.list
                echo "deb-src http://packages.icinga.com/ubuntu icinga-${DIST} main" >> /etc/apt/sources.list.d/${DIST}-icinga.list
            fi
        elif [[ ${ID} == "debian" ]]; then
            if [ ! -z ${VERSION_CODENAME+x} ]; then
                DIST="${VERSION_CODENAME}"
            else
                DIST="buster"
            fi

            if [ ! -f "/etc/apt/sources.list.d/${DIST}-icinga.list" ]; then
                wget -O - https://packages.icinga.com/icinga.key | apt-key add -
                echo "deb http://packages.icinga.com/debian icinga-${DIST} main" > /etc/apt/sources.list.d/${DIST}-icinga.list
                echo "deb-src http://packages.icinga.com/debian icinga-${DIST} main" >> /etc/apt/sources.list.d/${DIST}-icinga.list
            fi
        fi

        sleep 5
        apt-get update
        exit 0
        ;;
    upgrade|abort-upgrade)
        ;;
    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

exit 0
