name: Publish Release

on:
  workflow_run:
    workflows: ["Build Release"]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish_latest_release_to_package_server:
    name: Publish latest release to package server
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download assets from latest release
        uses: Itsblue/download-release-assets-action@v4
        with:
          file: ".*"
          path: "."
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy package to package server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REPO_SSH_HOST }}
          username: ${{ secrets.REPO_SSH_USER }}
          key: ${{ secrets.REPO_SSH_KEY }}
          port: 22
          source: "./*"
          target: ${{ secrets.REPO_SSH_INCOMING_PATH_NCM }}


      - name: Publish package
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REPO_SSH_HOST }}
          username: ${{ secrets.REPO_SSH_USER }}
          key: ${{ secrets.REPO_SSH_KEY }}
          port: 22
          script: /usr/local/bin/publish-debs ncm
